config/routes.rb
Cats99::Application.routes.draw do
  root to: 'cats#index'

  resources :cats, except: [:destroy]

  resources :cat_rental_requests, only: [:create, :new] do
    member do
      put 'approve'
      put 'deny'
    end
  end

  resources :users, only: [:create, :new]

  resources :sessions, only: [:create, :new, :destroy]
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :age, :birth_date, :color, :name, :sex, :user_id

  validates :age, :birth_date, :color, :name, :sex, :user_id, presence: true
  validates :age, numericality: { only_integer: true }
  validates :color,
    :inclusion => { :in => ['brown', 'black', 'red', 'orange', 'blue', 'yellow', 'green'] }
  validates :sex, :inclusion => { :in => ['F', 'M'] }

  has_many :cat_rental_requests,
  :foreign_key => :cat_id,
  :primary_key => :id,
  :class_name => "CatRentalRequest",
  :dependent => :destroy

  belongs_to :owner,
             :foreign_key => :user_id,
             :primary_key => :id,
             :class_name => "User"

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :start_date, :end_date, :status

  before_validation(on: :create) do
    self.status ||= 'PENDING'
  end

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, :inclusion =>
    { :in => ['PENDING', 'APPROVED', 'DENIED'] }


  belongs_to :cat,
  :foreign_key => :cat_id,
  :primary_key => :id,
  :class_name => "Cat"

  def approve!
    self.status = "APPROVED"
    self.save
    self.cat.cat_rental_requests.each do |request|
      request.deny! if overlapping_pending_requests.include?(request)
    end
  end

  def deny!
    self.status = "DENIED"
    self.save
  end

  def overlapping_requests
    self.cat.cat_rental_requests.where("(start_date > ? AND start_date < ?) OR
    (end_date > ? AND end_date < ?)", self.start_date, self.end_date, self.start_date, self.end_date
    )
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def overlapping_pending_requests
    overlapping_requests.where("status = 'PENDING'")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :session_token

  before_validation(:ensure_session_token, on: :create)

  validates :session_token, :username, presence: true

  has_many :cats,
           :foreign_key => :user_id,
           :primary_key => :id,
           :class_name => "Cat"

  # has_many :session_tokens,
  #          :foreign_key => :user_id,
  #          :primary_key => :id,
  #          :class_name => "SessionToken"

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end
  #
  def delete_session
    self.session_token.delete()

  end
    #
  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_filter :require_current_user!, :only => [:approve, :deny]

  def create
    @cat_rental_request = CatRentalRequest.new(params[:cat_rental_request])

    if @cat_rental_request.save
      redirect_to cats_url
    else
      render @cat_rental_request.errors.full_messages, status: :unprocessable_entity
    end
  end

  def new
    @cats = Cat.all
  end

  def approve
    @cat_rental_request = CatRentalRequest.find(params[:id])
    @cat_rental_request.approve!
    redirect_to cat_url(@cat_rental_request.cat_id)
  end

  def deny
    @cat_rental_request = CatRentalRequest.find(params[:id])
    @cat_rental_request.deny!
    redirect_to cat_url(@cat_rental_request.cat_id)
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_filter :require_current_user!, :only => [:edit, :update]

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new

    render :new
  end

  def create
    @cat = Cat.new(params[:cat])

    @cat.user_id = current_user.id

    if @cat.save
      redirect_to cats_url
    else
      render @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update_attributes(params[:cat])
      redirect_to cats_url
    else
      render @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user.nil?
      flash[:errors] = "WRONG CREDENTIALS!!!"
      redirect_to new_session_url
    else
      @user.reset_session_token!

      session[:session_token] = @user.session_token

      redirect_to cats_url
    end
  end

  def new
    render :new
  end

  def destroy
    session_token = session[:session_token]
    @user = User.find_by_session_token(session_token)

    session[:session_token] = nil
    @user.reset_session_token!

    redirect_to cats_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])

    if @user.save
      login_user!
    else
      render @user.errors.full_messages, status: :unprocessable_entity
    end
  end

  def new
    @user = User.new

    render :new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def login_user!
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
      )

    session[:session_token] = @user.session_token

    redirect_to cats_url
  end

  def require_current_user!
    if params[:controller] == "cat_rental_requests"
      @cat = CatRentalRequest.find(params[:id]).cat
    elsif params[:controller] == "cats"
      @cat = Cat.find(params[:id])
    end

    redirect_to cats_url if @cat.user_id != current_user.id
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<h2>Cat Rental Request</h2>
<form action="/cat_rental_requests" method="post">

  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="available_cats">Available Cats</label>
  <select name="cat_rental_request[cat_id]">
  <% @cats.each do |cat| %>
    <option value=<%= cat.id %>><%= cat.name %></option>
  <% end %>
  </select>

<p><label for="request_start_date">Start date</label>
<input name="cat_rental_request[start_date]" id="start_date" type="date"></input></p>

<p><label for="request_end_date">End date</label>
<input name="cat_rental_request[end_date]" id="end_date" type="date"></input></p>

<p><input type="submit" value="Select a cat"></p>


<p><a href="/cats/">Back to the cats!</a></p>

app/views/cats/_form.html.erb
<h2>Cat Form</h2>
<form action="/cats/<%= @cat.id %>" method="post">
  <input type='hidden' name='_method' value=<%= 'PUT' if @cat.persisted? %> >

  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <table bgcolor="c0c0c0">

  <tr align="left"><th><label for="cat_name">Name:</label>
  <td><input name="cat[name]" id="cat_name" type="text" value="<%= @cat.name %>">
  <br>

  <tr align="left"><th><label for="cat_age">Age:</label>
  <td><input name="cat[age]" id="cat_age" type="number" value="<%= @cat.age %>">
  <br>

  <tr align="left"><th><label>Sex:</label>

    <td><input name="cat[sex]" id="cat_sex_m" type="radio" value="M" <%= "checked"          if @cat.sex == "M" %>>
    <label for="cat_sex_m">Male</label>
    <input name="cat[sex]" id="cat_sex_f" type="radio" value="F" <%= "checked"          if @cat.sex == "F" %>>
    <label for="cat_sex_f">Female</label>

    <br>

  <tr align="left"><th><label for="cat_coat_color">Coat color:</label>
  <td><select name="cat[color]">
    <option value="brown"  <%= "selected" if @cat.color == "brown" %>
      >Brown</option>
    <option value="black"  <%= "selected" if @cat.color == "black" %>
      >Black</option>
    <option value="red"    <%= "selected" if @cat.color == "red" %>
      >Red</option>
    <option value="orange" <%= "selected" if @cat.color == "orange" %>
      >Orange</option>
    <option value="blue"   <%= "selected" if @cat.color == "blue" %>
      >Blue</option>
    <option value="yellow" <%= "selected" if @cat.color == "yellow" %>
      >Yellow</option>
    <option value="green"  <%= "selected" if @cat.color == "green" %>
      >Green</option>
  </select>
  <br>

  <tr align="left"><th><label for="cat_birth_date">Birth date:</label>
  <td><input name="cat[birth_date]" id="cat_birth_date" type="date" value=<%=
    @cat.birth_date%> ></input>

  </table>

    <br>

  <input type="submit" value="<%= @cat.persisted? ? 'Edit my cat!' : 'Add my cat!' %>">
</form>
<br>
<a href="/cats/">Back to the cats!</a>

app/views/cats/edit.html.erb
<%= render partial: 'form' %>

app/views/cats/index.html.erb
<title>99 Cats</title>

<h1>Welcome to 99 Cats! Meow!</h1>
<p>Log in or create an account to request a cat & add your cat!</p>

<h3>Our Current Cats</h3>

<ul>
  <% @cats.each do |cat| %>
    <li><a href="/cats/<%=cat.id%>"><%= cat.name.capitalize %></a></li>
    <br>
  <% end %>
</ul>

<% if current_user %>
  <a href="/cat_rental_requests/new">Request a cat!</a>
  <br>
  <br>
  <a href="/cats/new">Add a new cat!</a>
<% end %>

app/views/cats/new.html.erb
<%= render partial: 'form' %>

app/views/cats/show.html.erb
<table>

<tr align=left><th>Name:<td><%= @cat.name.capitalize %>
<tr align=left><th>Age:<td><%= @cat.age %>
<tr align=left><th>Sex:<td><%= @cat.sex %>
<tr align=left><th>Color:<td><%= @cat.color.capitalize %>
<tr align=left><th>Birth Date:<td><%= @cat.birth_date %>

</table>

<table>
  <h2>Current Rental Requests</h2>
  <th>Start Date</th><th>End Date</th>

  <% @cat.cat_rental_requests.each do |request| %>

    <tr><td><%= request.start_date %>

    <td><%= request.end_date %>

    <% unless current_user.nil? %>
      <% if request.status == "PENDING" && @cat.user_id == current_user.id %>

      <td><%= button_to "Approve",
          approve_cat_rental_request_url(request),
          :method => :put %>
      <td><%= button_to "Deny",
          deny_cat_rental_request_url(request),
          :method => :put %>

      <% end %>
    <% end %>

  <% end %>

</table>

  <br>

<% if !current_user.nil? && (@cat.user_id == current_user.id) %>
  <a href="/cats/<%= @cat.id %>/edit">Edit my cat!</a>

  <br>
<% end %>

<a href="/cats/">Back to the cats!</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>99Cats</title>
</head>
<body>

  <% if current_user %>

      Logged in as: <%= current_user.username %>
      <%= button_to "Logout", session_url(current_user), :method => :delete %>


  <% else %>
    <%= button_to "Login", new_session_url, :method => :get %>
    <%= button_to "Sign Up", new_user_url, :method => :get %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<form action="<%= users_url %>" method="post">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Enter a Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Enter a Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="Submit">
</form>